name: Build and Push Ollama Preloaded Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ollama-preloaded
  MODEL_NAME: llama3
  DOCKERHUB_USERNAME: rezerbleede
  GHCR_USERNAME: rezer-bleede

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------------
      # 🧹 Free up disk space before build
      # -------------------------------
      - name: Free disk space
        run: |
          echo "Before cleanup:"
          df -h
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc || true
          docker system prune -af || true
          echo "After cleanup:"
          df -h

      # -------------------------------
      # 🐳 Set up Docker Buildx
      # -------------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # -------------------------------
      # 🔑 Login to Docker registries
      # -------------------------------
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # -------------------------------
      # 🧱 Build the preloaded Ollama image
      # -------------------------------
      - name: Build image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --progress=plain \
            -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$MODEL_NAME \
            -t ghcr.io/$GHCR_USERNAME/$IMAGE_NAME:$MODEL_NAME \
            --push .

      # -------------------------------
      # ✅ Post-build cleanup
      # -------------------------------
      - name: Disk cleanup after build
        if: always()
        run: docker system prune -af || true
