name: Build and Push Ollama Preloaded Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ---- LOGIN TO REGISTRIES ----
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---- BUILD & PUSH MULTI-REGISTRY ----
      - name: Build and Push Image
        run: |
          IMAGE_NAME=ollama-preloaded:llama3
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ghcr.io/rezer-bleede/$IMAGE_NAME \
            -t rezerbleede/$IMAGE_NAME \
            --push .
