name: 🧠 Build & Push Ollama Preloaded (Multi-Arch)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Multi-Arch Images
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: llama3
            model_names: "llama3"
            default_model: "llama3"
          - tag: phi3-mini
            model_names: "phi3:mini"
            default_model: "phi3:mini"

    steps:
      # 1) Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Free disk space
      - name: Free disk space
        run: |
          echo "Cleaning space for large model layers..."
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost /usr/local/lib/android /opt/hostedtoolcache || true
          sudo apt-get clean
          docker system prune -af || true
          df -h || true

      # 3) Setup QEMU & Buildx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      # 4) Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5) Build & Push (matrix)
      - name: Build & Push ${{ matrix.tag }}
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t rezerbleede/ollama-preloaded:${{ matrix.tag }} \
            --build-arg MODEL_NAMES="${{ matrix.model_names }}" \
            --build-arg DEFAULT_MODEL="${{ matrix.default_model }}" \
            --build-arg STARTUP_WAIT_SECS=2200 \
            --push .

      # 6) Verify manifest
      - name: Verify manifest ${{ matrix.tag }}
        run: |
          docker buildx imagetools inspect rezerbleede/ollama-preloaded:${{ matrix.tag }}
